### ISSUE TITLE
誤字報告

### ISSUE THREAD

**Issue by yat8823jp** [shimakyohsuke/hiking-hiking#1]
# 誤字脱字などのご連絡はこちらから

## 誤字脱字があったページの URL
https://hiking-hiking.com/post/coffee-dripper/
<>

## 内容

- [ ] 背景がごちゃついててわかりずいらい
- [x] 背景がごちゃついててわかりずらい

**Comment by shimakyohsuke** [comment]
あざまっす！
https://github.com/shimakyohsuke/hiking-hiking/commit/5e414eb884c0c4a2d1af79c1afc5f48f233e4b27
対応しました！

**Comment by mismith0227** [comment]
あと、「ず」じゃなくて「づ」ですね。
分かり・辛いなので

**Comment by yat8823jp** [comment]
おお、ほんとだ！

**Comment by shimakyohsuke** [comment]
あざっす！
https://github.com/shimakyohsuke/hiking-hiking/commit/3ff77b1e04b0ff821340a3d256531e5e5dcd99c0
対応しました！

**Comment by shimakyohsuke** [comment]
Publish されたのでクローズします！ありがとうございました！
https://hiking-hiking.com/post/coffee-dripper/

**Comment by mismith0227** [comment]
[![LGTM](https://66.media.tumblr.com/6fbf1f59b91abc66feed17a36e587726/tumblr_oerdrfucgL1qa4mzvo4_500.gif)](https://lgtm.in/i/idUcDYbRp)

**Comment by yat8823jp** [comment]
<img src="http://i.gyazo.com/2e4b0bad9565b3166e30ac57e9cfce4f.png">
